apiVersion: carbon-aware-actions.cncf/dev
kind: CarbonAwareScaler
metadata:
 name: scaledown2
spec:
  kedaScaledObjectRef:
    name: httpj
  defaultMaxReplicaCount: 89 # when Carbon Intensiy is lower than 90 (lowest provided input)
  scalingRules:
    - carbonIntensity: 90  # if CarbonIntensity between 90 and 10 => set to MaxReplicaCount to 80
      allowedMaxReplicaCount: 81
    - carbonIntensity: 100
      allowedMaxReplicaCount: 53
    - carbonIntensity: 110
      allowedMaxReplicaCount: 44

